/**
 * Response DTO types, DERIVED FROM the Spring Boot OpenAPI schema (`lib/api/types.ts`,
 * generated by `pnpm gen:types` from the Java `/v3/api-docs`). This is the single source of
 * truth for the API's response shapes — re-exported by `@/lib/contract` under the same names
 * the app already uses, so no component changes are needed.
 *
 * springdoc emits every field as optional and a few genuinely-nullable/loose fields without
 * nullability, so we tighten with `Required<>` + explicit overrides to match the contract
 * (ARCHITECTURE.md §3). The auth `Session` (a discriminated union springdoc renders as an empty
 * object) stays defined in `dto/auth.ts`, where it is also runtime-validated.
 */
import type { components } from '@/lib/api/types';
import type { CompanyStatus } from './dto/companies';

type Schemas = components['schemas'];

// --- Companies (§3.3) ------------------------------------------------------

export type CompanyAdmin = Required<Schemas['CompanyAdminView']>;

export type CompanySummary = Omit<Required<Schemas['CompanySummaryView']>, 'status' | 'deletedAt'> & {
  status: CompanyStatus;
  deletedAt: string | null; // set only when archived
};

export type CompanyDetail = Omit<
  Required<Schemas['CompanyDetailView']>,
  'status' | 'admin' | 'deletedAt'
> & {
  status: CompanyStatus;
  deletedAt: string | null;
  admin: CompanyAdmin | null;
};

export type ProvisionCompanyAdminResult = Omit<
  Required<Schemas['ProvisionAdminResult']>,
  'admin' | 'devPassword'
> & {
  admin: CompanyAdmin;
  devPassword?: string;
};

export type PurgeCompanyResult = Required<Schemas['PurgeCompanyResult']>;

// --- Teams (§3.4) ----------------------------------------------------------

export type TeamMember = Required<Schemas['TeamMemberView']>;

export type TeamSummary = Omit<Required<Schemas['TeamSummaryView']>, 'hr' | 'manager' | 'accountant'> & {
  hr: TeamMember | null;
  manager: TeamMember | null;
  accountant: TeamMember | null;
};

export type TeamDetail = Omit<
  Required<Schemas['TeamDetailView']>,
  'hr' | 'manager' | 'accountant' | 'members'
> & {
  hr: TeamMember | null;
  manager: TeamMember | null;
  accountant: TeamMember | null;
  members: TeamMember[];
};

export type AssignableUser = TeamMember;

export type AssignMemberResult = Omit<
  Required<Schemas['AssignMemberResult']>,
  'team' | 'devPassword'
> & {
  team: TeamDetail;
  devPassword?: string;
};

// --- Employees (§3.5) ------------------------------------------------------

export type EmployeeSummary = Omit<
  Required<Schemas['EmployeeSummaryView']>,
  'employeeCode' | 'dateOfJoining'
> & {
  // employeeCode is null until the employee is approved (the ID is allocated then, §5).
  employeeCode: string | null;
  dateOfJoining: string | null;
};

export type OnboardEmployeeResult = Omit<
  Required<Schemas['OnboardEmployeeResult']>,
  'employee'
> & {
  employee: EmployeeSummary;
};

/** A page of the HR's onboarding queue. */
export type EmployeePage = Omit<Required<Schemas['EmployeePage']>, 'content'> & {
  content: EmployeeSummary[];
};

// --- Employee onboarding — the four-form stepper (§3.2) --------------------

/** The four form views come from the OpenAPI schema; fields may be null while drafting. */
export type Form1View = Schemas['Form1View'];
export type Form2View = Schemas['Form2View'];
export type Form3EntryView = Schemas['Form3EntryView'];
export type EducationalQualification = Schemas['EducationalQualification'];
export type WorkingExperience = Schemas['WorkingExperience'];
export type FamilyDetail = Schemas['FamilyDetail'];
export type CharacterReference = Schemas['CharacterReference'];
export type SignatureView = Required<Schemas['SignatureView']>;

export type DocumentDto = Omit<Required<Schemas['DocumentView']>, 'sha256' | 'groupIndex'> & {
  sha256: string | null;
  groupIndex: number | null;
};

export type GeneratedDocumentView = Omit<Required<Schemas['GeneratedDocumentView']>, 'sha256'> & {
  sha256: string | null;
};

export type OnboardingDashboard = Omit<
  Required<Schemas['OnboardingDashboard']>,
  'employeeCode' | 'fullName' | 'designation' | 'form1' | 'form2' | 'form3' | 'documents' | 'signature' | 'generatedDocuments'
> & {
  employeeCode: string | null;
  fullName: string | null;
  designation: string | null;
  form1: Form1View | null;
  form2: Form2View | null;
  form3: Form3EntryView[];
  documents: DocumentDto[];
  signature: SignatureView | null;
  generatedDocuments: GeneratedDocumentView[];
};

export type PresignedUpload = Required<Schemas['PresignedUpload']>;

export type PresignedView = Required<Schemas['PresignedView']>;

// --- HR verification & routing (§3.3/§3.4) --------------------------------

export type RecordDocument = Omit<Required<Schemas['RecordDocument']>, 'sha256' | 'groupIndex'> & {
  sha256: string | null;
  groupIndex: number | null;
};

export type RecordGeneratedDocument = Omit<Required<Schemas['RecordGeneratedDocument']>, 'sha256'> & {
  sha256: string | null;
};

export type EmployeeRecord = Omit<
  Required<Schemas['EmployeeRecordView']>,
  'employeeCode' | 'dateOfJoining' | 'form1' | 'form2' | 'form3' | 'documents' | 'generatedDocuments'
> & {
  // employeeCode is null until approval (§5); dateOfJoining may be absent on legacy rows.
  employeeCode: string | null;
  dateOfJoining: string | null;
  form1: Form1View | null;
  form2: Form2View | null;
  form3: Form3EntryView[];
  documents: RecordDocument[];
  generatedDocuments: RecordGeneratedDocument[];
};

/** Plaintext sensitive values returned by the explicit, audited reveal action (§6). */
export type RevealedSensitive = Omit<
  Required<Schemas['RevealedSensitive']>,
  'form1' | 'form2' | 'form3'
> & {
  form1: Form1View | null;
  form2: Form2View | null;
  form3: Form3EntryView[];
};

export type RouteToManagerResult = Omit<
  Required<Schemas['RouteToManagerResult']>,
  'managerName' | 'employeeCode'
> & {
  managerName: string | null;
  employeeCode: string | null;
};

// --- Manager inbox (§2/§3.3) ----------------------------------------------

export type NotificationItem = Omit<
  Required<Schemas['NotificationView']>,
  'employeeId' | 'employeeCode' | 'fullName'
> & {
  employeeId: string | null;
  employeeCode: string | null;
  fullName: string | null;
};

export type NotificationFeed = Omit<Required<Schemas['NotificationFeed']>, 'notifications'> & {
  notifications: NotificationItem[];
};

export type Approval = Omit<
  Required<Schemas['ApprovalView']>,
  'note' | 'decidedAt' | 'employeeCode' | 'fullName' | 'designation'
> & {
  note: string | null;
  // employeeCode is null until the Manager approves (the ID is minted then, §5).
  employeeCode: string | null;
  decidedAt: string | null;
  fullName: string | null;
  designation: string | null;
};

// --- Audit explorer (§7) --------------------------------------------------

export type AuditLogEntry = Omit<
  Required<Schemas['AuditLogView']>,
  'actorId' | 'companyName' | 'targetType' | 'targetId' | 'targetLabel' | 'ipAddress' | 'metadata'
> & {
  actorId: string | null;
  companyName: string | null;
  targetType: string | null;
  targetId: string | null;
  // Resolved employee name when the target is an Employee (e.g. approval events); else null.
  targetLabel: string | null;
  ipAddress: string | null;
  metadata: Record<string, unknown> | null;
};

export type AuditLogPage = Omit<Required<Schemas['AuditPage']>, 'content'> & {
  content: AuditLogEntry[];
};

// --- Role dashboard (§2/§7/§9) --------------------------------------------

export type StatCard = Required<Schemas['StatCard']>;

/** {@code company} is present only for the Super Admin's portfolio feed. */
export type ActivityItem = Schemas['ActivityItem'];

export type EmployeeProgress = Omit<Required<Schemas['EmployeeProgress']>, 'employeeId'> & {
  employeeId: string | null;
};

export type DashboardSummary = Omit<
  Required<Schemas['DashboardSummary']>,
  'stats' | 'recentActivity' | 'employeeProgress'
> & {
  stats: StatCard[];
  recentActivity: ActivityItem[];
  employeeProgress: EmployeeProgress | null;
};

// --- Accountant (cross-company, read-only, approved employees; §2/§6) ------

export type AccountantView = Required<Schemas['AccountantView']>;

/** {@code accountant} is present only once the singleton exists. */
export type AccountantStatus = Omit<Required<Schemas['AccountantStatus']>, 'accountant'> & {
  accountant: AccountantView | null;
};

export type ProvisionAccountantResult = Omit<
  Required<Schemas['ProvisionAccountantResult']>,
  'devPassword'
> & {
  devPassword: string | null;
};

/** One row of the cross-company approved-employees table. */
export type ApprovedEmployeeRow = Schemas['ApprovedEmployeeRow'];

export type ApprovedEmployeePage = Omit<Required<Schemas['ApprovedEmployeePage']>, 'content'> & {
  content: ApprovedEmployeeRow[];
};
