/**
 * Response DTO types, DERIVED FROM the Spring Boot OpenAPI schema (`lib/api/types.ts`,
 * generated by `pnpm gen:types` from the Java `/v3/api-docs`). This is the single source of
 * truth for the API's response shapes — re-exported by `@/lib/contract` under the same names
 * the app already uses, so no component changes are needed.
 *
 * springdoc emits every field as optional and a few genuinely-nullable/loose fields without
 * nullability, so we tighten with `Required<>` + explicit overrides to match the contract
 * (ARCHITECTURE.md §3). The auth `Session` (a discriminated union springdoc renders as an empty
 * object) stays defined in `dto/auth.ts`, where it is also runtime-validated.
 */
import type { components } from '@/lib/api/types';
import type { CompanyStatus } from './dto/companies';

type Schemas = components['schemas'];

// --- Companies (§3.3) ------------------------------------------------------

export type CompanyAdmin = Required<Schemas['CompanyAdminView']>;

export type CompanySummary = Omit<Required<Schemas['CompanySummaryView']>, 'status'> & {
  status: CompanyStatus;
};

export type CompanyDetail = Omit<Required<Schemas['CompanyDetailView']>, 'status' | 'admin'> & {
  status: CompanyStatus;
  admin: CompanyAdmin | null;
};

export type ProvisionCompanyAdminResult = Omit<
  Required<Schemas['ProvisionAdminResult']>,
  'admin' | 'devPassword'
> & {
  admin: CompanyAdmin;
  devPassword?: string;
};

// --- Teams (§3.4) ----------------------------------------------------------

export type TeamMember = Required<Schemas['TeamMemberView']>;

export type TeamSummary = Omit<Required<Schemas['TeamSummaryView']>, 'hr' | 'manager'> & {
  hr: TeamMember | null;
  manager: TeamMember | null;
};

export type TeamDetail = Omit<
  Required<Schemas['TeamDetailView']>,
  'hr' | 'manager' | 'members'
> & {
  hr: TeamMember | null;
  manager: TeamMember | null;
  members: TeamMember[];
};

export type AssignableUser = TeamMember;

export type AssignMemberResult = Omit<
  Required<Schemas['AssignMemberResult']>,
  'team' | 'devPassword'
> & {
  team: TeamDetail;
  devPassword?: string;
};

// --- Employees (§3.5) ------------------------------------------------------

export type EmployeeSummary = Omit<
  Required<Schemas['EmployeeSummaryView']>,
  'employeeCode' | 'dateOfJoining'
> & {
  // employeeCode is null until the employee is approved (the ID is allocated then, §5).
  employeeCode: string | null;
  dateOfJoining: string | null;
};

export type OnboardEmployeeResult = Omit<
  Required<Schemas['OnboardEmployeeResult']>,
  'employee'
> & {
  employee: EmployeeSummary;
};

// --- Employee onboarding (§3.6) -------------------------------------------

export type ProfileSectionDto = Omit<Required<Schemas['ProfileSectionView']>, 'data'> & {
  data: Record<string, unknown>;
};

export type DocumentDto = Omit<Required<Schemas['DocumentView']>, 'sha256'> & {
  sha256: string | null;
};

export type OnboardingDashboard = Omit<
  Required<Schemas['OnboardingDashboard']>,
  'sections' | 'documents'
> & {
  sections: ProfileSectionDto[];
  documents: DocumentDto[];
};

export type PresignedUpload = Required<Schemas['PresignedUpload']>;

export type PresignedView = Required<Schemas['PresignedView']>;

// --- HR verification & routing (§3.3/§3.4) --------------------------------

export type RecordSection = Omit<Required<Schemas['RecordSection']>, 'data'> & {
  data: Record<string, unknown>;
};

export type RecordDocument = Omit<Required<Schemas['RecordDocument']>, 'sha256'> & {
  sha256: string | null;
};

export type EmployeeRecord = Omit<
  Required<Schemas['EmployeeRecordView']>,
  'sections' | 'documents'
> & {
  sections: RecordSection[];
  documents: RecordDocument[];
};

export type RouteToManagerResult = Omit<
  Required<Schemas['RouteToManagerResult']>,
  'managerName'
> & {
  managerName: string | null;
};

// --- Manager inbox (§2/§3.3) ----------------------------------------------

export type NotificationItem = Omit<
  Required<Schemas['NotificationView']>,
  'employeeId' | 'employeeCode'
> & {
  employeeId: string | null;
  employeeCode: string | null;
};

export type NotificationFeed = Omit<Required<Schemas['NotificationFeed']>, 'notifications'> & {
  notifications: NotificationItem[];
};

export type Approval = Omit<Required<Schemas['ApprovalView']>, 'note' | 'decidedAt'> & {
  note: string | null;
  decidedAt: string | null;
};

// --- Audit explorer (§7) --------------------------------------------------

export type AuditLogEntry = Omit<
  Required<Schemas['AuditLogView']>,
  'actorId' | 'targetType' | 'targetId' | 'ipAddress' | 'metadata'
> & {
  actorId: string | null;
  targetType: string | null;
  targetId: string | null;
  ipAddress: string | null;
  metadata: Record<string, unknown> | null;
};

export type AuditLogPage = Omit<Required<Schemas['AuditPage']>, 'content'> & {
  content: AuditLogEntry[];
};
