/**
 * Response DTO types, DERIVED FROM the Spring Boot OpenAPI schema (`lib/api/types.ts`,
 * generated by `pnpm gen:types` from the Java `/v3/api-docs`). This is the single source of
 * truth for the API's response shapes — re-exported by `@/lib/contract` under the same names
 * the app already uses, so no component changes are needed.
 *
 * springdoc emits every field as optional and a few genuinely-nullable/loose fields without
 * nullability, so we tighten with `Required<>` + explicit overrides to match the contract
 * (ARCHITECTURE.md §3). The auth `Session` (a discriminated union springdoc renders as an empty
 * object) stays defined in `dto/auth.ts`, where it is also runtime-validated.
 */
import type { components } from '@/lib/api/types';
import type { CompanyStatus } from './dto/companies';

type Schemas = components['schemas'];

// --- Companies (§3.3) ------------------------------------------------------

export type CompanyAdmin = Required<Schemas['CompanyAdminView']>;

export type CompanySummary = Omit<Required<Schemas['CompanySummaryView']>, 'status' | 'deletedAt'> & {
  status: CompanyStatus;
  deletedAt: string | null; // set only when archived
};

export type CompanyDetail = Omit<
  Required<Schemas['CompanyDetailView']>,
  'status' | 'admin' | 'deletedAt'
> & {
  status: CompanyStatus;
  deletedAt: string | null;
  admin: CompanyAdmin | null;
};

export type ProvisionCompanyAdminResult = Omit<
  Required<Schemas['ProvisionAdminResult']>,
  'admin' | 'devPassword'
> & {
  admin: CompanyAdmin;
  devPassword?: string;
};

export type PurgeCompanyResult = Required<Schemas['PurgeCompanyResult']>;

// --- Teams (§3.4) ----------------------------------------------------------

export type TeamMember = Required<Schemas['TeamMemberView']>;

export type TeamSummary = Omit<Required<Schemas['TeamSummaryView']>, 'hr' | 'manager' | 'accountant'> & {
  hr: TeamMember | null;
  manager: TeamMember | null;
  accountant: TeamMember | null;
};

export type TeamDetail = Omit<
  Required<Schemas['TeamDetailView']>,
  'hr' | 'manager' | 'accountant' | 'members'
> & {
  hr: TeamMember | null;
  manager: TeamMember | null;
  accountant: TeamMember | null;
  members: TeamMember[];
};

export type AssignableUser = TeamMember;

export type AssignMemberResult = Omit<
  Required<Schemas['AssignMemberResult']>,
  'team' | 'devPassword'
> & {
  team: TeamDetail;
  devPassword?: string;
};

// --- Employees (§3.5) ------------------------------------------------------

export type EmployeeSummary = Omit<
  Required<Schemas['EmployeeSummaryView']>,
  'employeeCode' | 'dateOfJoining'
> & {
  // employeeCode is null until the employee is approved (the ID is allocated then, §5).
  employeeCode: string | null;
  dateOfJoining: string | null;
};

export type OnboardEmployeeResult = Omit<
  Required<Schemas['OnboardEmployeeResult']>,
  'employee'
> & {
  employee: EmployeeSummary;
};

/** A page of the HR's onboarding queue. */
export type EmployeePage = Omit<Required<Schemas['EmployeePage']>, 'content'> & {
  content: EmployeeSummary[];
};

// --- Employee onboarding — the four-form stepper (§3.2) --------------------

/** The four form views come from the OpenAPI schema; fields may be null while drafting. */
export type Form1View = Schemas['Form1View'];
export type Form2View = Schemas['Form2View'];
export type Form3EntryView = Schemas['Form3EntryView'];
export type EducationalQualification = Schemas['EducationalQualification'];
export type FamilyDetail = Schemas['FamilyDetail'];
export type CharacterReference = Schemas['CharacterReference'];
export type SignatureView = Required<Schemas['SignatureView']>;

export type DocumentDto = Omit<Required<Schemas['DocumentView']>, 'sha256' | 'groupIndex'> & {
  sha256: string | null;
  groupIndex: number | null;
};

export type GeneratedDocumentView = Omit<Required<Schemas['GeneratedDocumentView']>, 'sha256'> & {
  sha256: string | null;
};

// The employee dashboard covers Forms 1, 3, 4 only — Form 2 is HR/SA-authored and never exposed to the
// employee (no view; its standalone PDF is filtered out of generatedDocuments — §3.2).
export type OnboardingDashboard = Omit<
  Required<Schemas['OnboardingDashboard']>,
  'employeeCode' | 'fullName' | 'designation' | 'form1' | 'form3' | 'documents' | 'signature' | 'generatedDocuments'
> & {
  employeeCode: string | null;
  fullName: string | null;
  designation: string | null;
  form1: Form1View | null;
  form3: Form3EntryView[];
  documents: DocumentDto[];
  signature: SignatureView | null;
  generatedDocuments: GeneratedDocumentView[];
};

export type PresignedUpload = Required<Schemas['PresignedUpload']>;

export type PresignedView = Required<Schemas['PresignedView']>;

// --- HR verification & routing (§3.3/§3.4) --------------------------------

export type RecordDocument = Omit<Required<Schemas['RecordDocument']>, 'sha256' | 'groupIndex'> & {
  sha256: string | null;
  groupIndex: number | null;
};

export type RecordGeneratedDocument = Omit<Required<Schemas['RecordGeneratedDocument']>, 'sha256'> & {
  sha256: string | null;
};

export type EmployeeRecord = Omit<
  Required<Schemas['EmployeeRecordView']>,
  | 'employeeCode'
  | 'dateOfJoining'
  | 'mailAddress'
  | 'mailDomain'
  | 'form1'
  | 'form2'
  | 'form3'
  | 'documents'
  | 'generatedDocuments'
  | 'aadhaarNumber'
  | 'agreements'
> & {
  // employeeCode is null until approval (§5); dateOfJoining may be absent on legacy rows.
  employeeCode: string | null;
  dateOfJoining: string | null;
  // Read-only mailbox state (§8, Stage 5): null until credentials are assigned (credentialsAssigned=false).
  mailAddress: string | null;
  // The company's mail domain — drives the assign-mailbox preview so it matches the real address.
  mailDomain: string | null;
  form1: Form1View | null;
  form2: Form2View | null;
  form3: Form3EntryView[];
  documents: RecordDocument[];
  generatedDocuments: RecordGeneratedDocument[];
  // Aadhaar (§Agreements): masked ("********") when present, null when not yet provided; revealed via /reveal.
  aadhaarNumber: string | null;
  // Post-approval agreements (§Agreements): per-type status + presigned download when completed.
  agreements: AgreementSummary[];
};

/** Plaintext sensitive values returned by the explicit, audited reveal action (§6). */
export type RevealedSensitive = Omit<
  Required<Schemas['RevealedSensitive']>,
  'form1' | 'form2' | 'form3' | 'aadhaarNumber'
> & {
  form1: Form1View | null;
  form2: Form2View | null;
  form3: Form3EntryView[];
  aadhaarNumber: string | null;
};

// --- Post-approval agreements (§Agreements) --------------------------------

/** One agreement in the HR record / send result; downloadUrl is null until completed. */
export type AgreementSummary = Omit<
  Required<Schemas['AgreementSummary']>,
  'sentAt' | 'completedAt' | 'sentByName' | 'downloadUrl'
> & {
  sentAt: string | null;
  completedAt: string | null;
  sentByName: string | null;
  downloadUrl: string | null;
};

export type SendAgreementsResult = { agreements: AgreementSummary[] };

/** Prefill values for the employee fill screen; edited values are stamped into the PDF only. */
export type AgreementPrefill = Required<Schemas['AgreementPrefill']>;

/** A row in the employee's own agreements list. */
export type MyAgreementSummary = Omit<Required<Schemas['MyAgreementSummary']>, 'completedAt'> & {
  completedAt: string | null;
};

/** A single agreement the employee reads and fills. */
export type MyAgreementView = Omit<
  Required<Schemas['MyAgreementView']>,
  'completedAt' | 'downloadUrl' | 'prefill'
> & {
  completedAt: string | null;
  downloadUrl: string | null;
  prefill: AgreementPrefill;
};

/** Result of completing one agreement — its COMPLETED state + a presigned link to the stored PDF. */
export type CompleteAgreementResult = Omit<Required<Schemas['CompleteAgreementResult']>, 'downloadUrl'> & {
  downloadUrl: string | null;
};

/** The three standard agreement types (§Agreements). */
export type AgreementType = NonNullable<Schemas['AgreementSummary']['type']>;
export type AgreementStatus = NonNullable<Schemas['AgreementSummary']['status']>;

// The HR approve/reject outcome (§3.3). On approve: employeeCode minted + team/manager set. On reject:
// all of these are null (the employee joined no team) — so override every one as nullable.
export type DecisionResult = Omit<
  Required<Schemas['DecisionResult']>,
  'employeeCode' | 'teamId' | 'teamName' | 'managerName'
> & {
  employeeCode: string | null;
  teamId: string | null;
  teamName: string | null;
  managerName: string | null;
};


/** The mailbox address HR assigned; {@code password} is echoed ONCE (dev) so HR can hand it over (§8). */
export type AssignCredentialsResult = Omit<Required<Schemas['AssignCredentialsResult']>, 'password'> & {
  password: string | null;
};

// --- Leave (§8b) -----------------------------------------------------------

/** The employee's own leave request; decision fields are null until decided. */
export type LeaveRequest = Omit<
  Required<Schemas['LeaveRequestView']>,
  'decisionNote' | 'decidedAt'
> & {
  decisionNote: string | null;
  decidedAt: string | null;
};

/** A row in the Manager's leave queue — carries the employee's identity. */
export type TeamLeaveRow = Omit<
  Required<Schemas['TeamLeaveRow']>,
  'employeeCode' | 'employeeName' | 'decisionNote' | 'decidedAt'
> & {
  employeeCode: string | null;
  employeeName: string | null;
  decisionNote: string | null;
  decidedAt: string | null;
};

export type LeaveMinePage = Omit<Required<Schemas['LeaveMinePage']>, 'content'> & {
  content: LeaveRequest[];
};

export type TeamLeavePage = Omit<Required<Schemas['TeamLeavePage']>, 'content'> & {
  content: TeamLeaveRow[];
};

// --- HR/Accounts Requests (§8d) --------------------------------------------

/** A fulfilment file's metadata (never the storage key). */
export type RequestDocumentView = Required<Schemas['RequestDocumentView']>;

/** The employee's own request; nullable fields are null until set. */
export type DocumentRequestView = Omit<
  Required<Schemas['DocumentRequestView']>,
  'note' | 'resolveNote' | 'pickedUpAt' | 'resolvedAt' | 'documents'
> & {
  note: string | null;
  resolveNote: string | null;
  pickedUpAt: string | null;
  resolvedAt: string | null;
  documents: RequestDocumentView[];
};

/** A row in the Accountant's queue — carries the employee's identity + their team. */
export type TeamRequestRow = Omit<
  Required<Schemas['TeamRequestRow']>,
  | 'employeeCode'
  | 'employeeName'
  | 'teamName'
  | 'note'
  | 'resolveNote'
  | 'pickedUpAt'
  | 'resolvedAt'
  | 'documents'
> & {
  employeeCode: string | null;
  employeeName: string | null;
  teamName: string | null;
  note: string | null;
  resolveNote: string | null;
  pickedUpAt: string | null;
  resolvedAt: string | null;
  documents: RequestDocumentView[];
};

/** The presigned PUT envelope for a fulfilment upload. */
export type RequestUpload = Required<Schemas['RequestUpload']>;

export type MyRequestsPage = Omit<Required<Schemas['MyRequestsPage']>, 'content'> & {
  content: DocumentRequestView[];
};

export type TeamRequestsPage = Omit<Required<Schemas['TeamRequestsPage']>, 'content'> & {
  content: TeamRequestRow[];
};

// --- Attendance (§8a) ------------------------------------------------------

/** Button + prompt state + worked totals (§8a v2); nullable fields are null when the state is absent. */
export type ClockStatus = Omit<
  Required<Schemas['ClockStatusView']>,
  'openSince' | 'breakOpenSince'
> & {
  openSince: string | null;
  breakOpenSince: string | null;
};

/** One break within a session; {@code breakEndAt} + {@code durationSeconds} are null while open. */
export type AttendanceBreakDto = Omit<
  Required<Schemas['AttendanceBreakView']>,
  'breakEndAt' | 'durationSeconds'
> & {
  breakEndAt: string | null;
  durationSeconds: number | null;
};

/** One session; {@code workedSeconds} (duration minus breaks) is null while open; breaks are nested. */
export type AttendanceSessionDto = Omit<
  Required<Schemas['AttendanceSessionView']>,
  'clockOutAt' | 'workedSeconds' | 'lateMinutes' | 'breaks'
> & {
  clockOutAt: string | null;
  workedSeconds: number | null;
  lateMinutes: number | null;
  breaks: AttendanceBreakDto[];
};

export type AttendanceDay = Omit<Required<Schemas['AttendanceDayView']>, 'sessions'> & {
  sessions: AttendanceSessionDto[];
};

export type MyAttendancePage = Omit<Required<Schemas['MyAttendancePage']>, 'days'> & {
  days: AttendanceDay[];
};

export type TeamAttendanceRow = Required<Schemas['TeamAttendanceRow']>;

/** One clock in/out event in the Manager's activity feed. */
export type TeamActivityEvent = Omit<
  Required<Schemas['TeamActivityEvent']>,
  'employeeCode' | 'fullName'
> & {
  employeeCode: string | null;
  fullName: string | null;
};

export type TeamActivityPage = Omit<Required<Schemas['TeamActivityPage']>, 'content'> & {
  content: TeamActivityEvent[];
};

// --- Manager inbox (§2/§3.3) ----------------------------------------------

export type NotificationItem = Omit<
  Required<Schemas['NotificationView']>,
  'employeeId' | 'employeeCode' | 'fullName'
> & {
  employeeId: string | null;
  employeeCode: string | null;
  fullName: string | null;
};

export type NotificationFeed = Omit<Required<Schemas['NotificationFeed']>, 'notifications'> & {
  notifications: NotificationItem[];
};

export type Approval = Omit<
  Required<Schemas['ApprovalView']>,
  'note' | 'decidedAt' | 'employeeCode' | 'fullName' | 'designation'
> & {
  note: string | null;
  // employeeCode is null until the Manager approves (the ID is minted then, §5).
  employeeCode: string | null;
  decidedAt: string | null;
  fullName: string | null;
  designation: string | null;
};

// --- Audit explorer (§7) --------------------------------------------------

export type AuditLogEntry = Omit<
  Required<Schemas['AuditLogView']>,
  'actorId' | 'companyName' | 'targetType' | 'targetId' | 'targetLabel' | 'ipAddress' | 'metadata'
> & {
  actorId: string | null;
  companyName: string | null;
  targetType: string | null;
  targetId: string | null;
  // Resolved employee name when the target is an Employee (e.g. approval events); else null.
  targetLabel: string | null;
  ipAddress: string | null;
  metadata: Record<string, unknown> | null;
};

export type AuditLogPage = Omit<Required<Schemas['AuditPage']>, 'content'> & {
  content: AuditLogEntry[];
};

// --- Role dashboard (§2/§7/§9) --------------------------------------------

export type StatCard = Required<Schemas['StatCard']>;

/** {@code company} is present only for the Super Admin's portfolio feed. */
export type ActivityItem = Schemas['ActivityItem'];

export type EmployeeProgress = Omit<Required<Schemas['EmployeeProgress']>, 'employeeId'> & {
  employeeId: string | null;
};

export type DashboardSummary = Omit<
  Required<Schemas['DashboardSummary']>,
  'stats' | 'recentActivity' | 'employeeProgress'
> & {
  stats: StatCard[];
  recentActivity: ActivityItem[];
  employeeProgress: EmployeeProgress | null;
};

// --- Accountant (cross-company, read-only, approved employees; §2/§6) ------

export type AccountantView = Required<Schemas['AccountantView']>;

/** {@code accountant} is present only once the singleton exists. */
export type AccountantStatus = Omit<Required<Schemas['AccountantStatus']>, 'accountant'> & {
  accountant: AccountantView | null;
};

export type ProvisionAccountantResult = Omit<
  Required<Schemas['ProvisionAccountantResult']>,
  'devPassword'
> & {
  devPassword: string | null;
};

// --- Hierarchy (cross-platform, read-only, aggregates-only; §2/§6) ----------

export type HierarchyView = Required<Schemas['HierarchyView']>;

/** {@code hierarchy} is present only once the singleton exists. */
export type HierarchyStatus = Omit<Required<Schemas['HierarchyStatus']>, 'hierarchy'> & {
  hierarchy: HierarchyView | null;
};

export type ProvisionHierarchyResult = Omit<
  Required<Schemas['ProvisionHierarchyResult']>,
  'devPassword'
> & {
  devPassword: string | null;
};

/** One row of the cross-company approved-employees table. */
export type ApprovedEmployeeRow = Schemas['ApprovedEmployeeRow'];

export type ApprovedEmployeePage = Omit<Required<Schemas['ApprovedEmployeePage']>, 'content'> & {
  content: ApprovedEmployeeRow[];
};

// Team-wise browsing (§2): ACCOUNTS_ADMIN company -> team -> employee; ACCOUNTANT own team.
export type ViewerCompanyRow = Required<Schemas['ViewerCompanyRow']>;
export type ViewerTeamRow = Required<Schemas['ViewerTeamRow']>;
export type MyTeamView = Required<Schemas['MyTeamView']>;

// Viewer attendance analytics (§8a) — live-computed metrics (Prompt-2 endpoints). These come fully
// populated from the server, so deep-require the (otherwise all-optional) generated shapes.
type DeepRequired<T> = T extends (infer U)[]
  ? DeepRequired<U>[]
  : T extends object
    ? { [K in keyof T]-?: DeepRequired<NonNullable<T[K]>> }
    : T;

export type LeavesByType = DeepRequired<Schemas['LeavesByType']>;
export type TimeComposition = DeepRequired<Schemas['TimeComposition']>;
// adherencePct is genuinely nullable at runtime (N/A when expectedDays = 0) and `month` is null for a
// custom from/to range (no single month); DeepRequired strips both nulls, so override them here — and
// re-nest the corrected summary inside the monthly series. periodStart/periodEnd always carry the window.
export type EmployeeMonthSummary = Omit<
  DeepRequired<Schemas['EmployeeMonthSummary']>,
  'adherencePct' | 'month'
> & {
  adherencePct: number | null;
  month: string | null;
  periodStart: string;
  periodEnd: string;
};
export type EmployeeMonthlySeries = Omit<DeepRequired<Schemas['EmployeeMonthlySeries']>, 'months'> & {
  months: EmployeeMonthSummary[];
};
export type TeamAttendanceMemberRow = DeepRequired<Schemas['TeamAttendanceMemberRow']>;
export type TeamAttendanceSummary = Omit<
  DeepRequired<Schemas['TeamAttendanceSummary']>,
  'employees' | 'month' | 'teamAdherencePct'
> & {
  employees: TeamAttendanceMemberRow[];
  month: string | null;
  periodStart: string;
  periodEnd: string;
  // Nullable at runtime (N/A when Σ expectedDays = 0), like adherencePct — DeepRequired strips the null.
  teamAdherencePct: number | null;
};

// --- Hierarchy platform overview (§2) — cross-company aggregates, server-populated ----
// Nullable at runtime: averageTimeToApprovalDays (null when none approved) and the StaffRef slots
// (absent when a company-admin / team slot is unassigned) — overridden so the UI shows "—".
export type StaffTotals = DeepRequired<Schemas['StaffTotals']>;
export type CompanyTotals = DeepRequired<Schemas['CompanyTotals']>;
export type PlatformTotals = DeepRequired<Schemas['PlatformTotals']>;
export type OnboardingFunnel = DeepRequired<Schemas['OnboardingFunnel']>;
export type StuckStage = DeepRequired<Schemas['StuckStage']>;
export type OpsMetrics = Omit<
  DeepRequired<Schemas['OpsMetrics']>,
  'averageTimeToApprovalDays' | 'stuckByStage'
> & {
  averageTimeToApprovalDays: number | null;
  stuckByStage: StuckStage[];
};
export type PlatformOverview = {
  totals: PlatformTotals;
  funnel: OnboardingFunnel;
  statusDistribution: OnboardingFunnel;
  ops: OpsMetrics;
};

export type TrendPoint = DeepRequired<Schemas['TrendPoint']>;
export type TrendsResponse = Omit<DeepRequired<Schemas['TrendsResponse']>, 'series'> & {
  series: TrendPoint[];
};

export type CompanySizeRow = DeepRequired<Schemas['CompanySizeRow']>;
export type CompaniesResponse = Omit<DeepRequired<Schemas['CompaniesResponse']>, 'companies'> & {
  companies: CompanySizeRow[];
};

export type StaffRef = DeepRequired<Schemas['StaffRef']>;
export type TeamBreakdown = Omit<
  DeepRequired<Schemas['TeamBreakdown']>,
  'hr' | 'manager' | 'accountant'
> & {
  hr: StaffRef | null;
  manager: StaffRef | null;
  accountant: StaffRef | null;
};
export type CompanyBreakdown = Omit<
  DeepRequired<Schemas['CompanyBreakdown']>,
  'byStatus' | 'companyAdmin' | 'teams'
> & {
  byStatus: OnboardingFunnel;
  companyAdmin: StaffRef | null;
  teams: TeamBreakdown[];
};

// --- Internal mail — thread-based (§8, Stage 3) ----------------------------

/** A mail participant — a staff account shown by name + `localpart@domain` address. */
export type MailParty = Required<Schemas['MailPartyView']>;

/** Attachment metadata shown on a message — never the storage key (§6/§8). */
export type MailAttachment = Required<Schemas['AttachmentView']>;

/** One of the viewer's labels (a tag on a thread) — the chip shape. */
export type MailLabelRef = Required<Schemas['LabelRef']>;

/** One of the viewer's labels with its thread-tag count (the rail list). */
export type MailLabel = Required<Schemas['LabelView']>;

/** One row in an Inbox / Sent / Search list — a THREAD from the viewer's perspective. */
export type ThreadListItem = Omit<Required<Schemas['ThreadListItemView']>, 'participants' | 'labels'> & {
  participants: MailParty[];
  labels: MailLabelRef[];
};

export type ThreadPage = Omit<Required<Schemas['ThreadPage']>, 'content'> & {
  content: ThreadListItem[];
};

/**
 * One message inside an open thread; `mine` marks the viewer's own messages. `to`/`cc`/`bcc` are the
 * recipients VISIBLE to this viewer (the server hides other recipients' BCC — `bcc` is non-empty only on
 * the sender's own copy, or shows a BCC recipient themselves).
 */
export type ThreadMessage = Omit<
  Required<Schemas['ThreadMessageView']>,
  'from' | 'to' | 'cc' | 'bcc' | 'attachments'
> & {
  from: MailParty;
  to: MailParty[];
  cc: MailParty[];
  bcc: MailParty[];
  attachments: MailAttachment[];
};

/** The presigned PUT + the draft attachment id to send once the upload completes. */
export type MailAttachmentUpload = Required<Schemas['AttachmentUpload']>;

/** An open thread: its messages in order + the counterparty a reply would go to. */
export type ThreadDetail = Omit<
  Required<Schemas['ThreadDetailView']>,
  'participants' | 'counterparty' | 'messages' | 'labels'
> & {
  participants: MailParty[];
  counterparty: MailParty | null;
  messages: ThreadMessage[];
  labels: MailLabelRef[];
};

export type MailUnreadCount = Required<Schemas['UnreadCountView']>;

/** The created message + the thread it lives in (so the client can open the thread). */
export type SendMessageResult = Required<Schemas['SendMessageResult']>;

// --- Drafts — author-private, unsent (§8) ----------------------------------

/** Save/replace a draft — permissive; every field is optional (nothing is required or graph-checked). */
export type SaveDraftInput = Schemas['SaveDraftRequest'];

/** One row in the Drafts list — a preview of an unsent composition (author-only). */
export type DraftListItem = Omit<Required<Schemas['DraftListItemView']>, 'recipients'> & {
  recipients: MailParty[];
};

export type DraftPage = Omit<Required<Schemas['DraftPage']>, 'content'> & {
  content: DraftListItem[];
};

/** A draft opened for editing — everything the composer needs to reopen it. */
export type Draft = Omit<Required<Schemas['DraftView']>, 'to' | 'cc' | 'bcc' | 'attachments'> & {
  to: MailParty[];
  cc: MailParty[];
  bcc: MailParty[];
  attachments: MailAttachment[];
};
