package com.ihrms.domain.support;

import static java.lang.annotation.ElementType.FIELD;
import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

import java.lang.annotation.Retention;
import java.lang.annotation.Target;
import org.hibernate.annotations.IdGeneratorType;

/** Marks a String {@code @Id} as generated by {@link CuidGenerator}. */
@IdGeneratorType(CuidGenerator.class)
@Retention(RUNTIME)
@Target({FIELD, METHOD})
public @interface CuidId {}
