import { apiFetch } from './client';

/**
 * Time & Attendance (iClock) admin surface — `/provisioning/iclock/**`.
 *
 * The types are hand-written here rather than re-exported from `@/lib/contract`: that module derives
 * response DTOs from `lib/api/openapi.json`, a CHECKED-IN snapshot regenerated by `pnpm gen:types`
 * against a running API. Regenerating it to pick up P1b would rewrite all 919 lines of `responses.ts`
 * in the same commit that introduces the console, burying the change. These shapes mirror
 * `IclockAdminDtos`, `IclockRosterDtos`, `IclockBoardService` and `IclockRosterService` one-for-one; a
 * later `gen:types` run can fold them in.
 *
 * Site scoping is a QUERY PARAM, never a tenant slug. A site spans companies (V43 links many companies
 * to one site), and SUPER_ADMIN has no `companySlug` at all — `RequireCompany` bounces every PLATFORM
 * role off `/[companySlug]/**`. So the console lives under `/super-admin/` and carries `?site=`.
 */

// --- sites -----------------------------------------------------------------

export interface IclockSite {
  id: string;
  name: string;
  timezone: string;
  companyCount: number;
  deviceCount: number;
  pinCount: number;
  createdAt: string;
}

export interface IclockSiteCompany {
  companyId: string;
  name: string;
  slug: string;
  archived: boolean;
}

export interface IclockSiteDetail {
  site: IclockSite;
  companies: IclockSiteCompany[];
  devices: IclockDevice[];
}

// --- devices ---------------------------------------------------------------

export interface IclockDevice {
  id: string;
  serialNumber: string;
  name: string | null;
  status: string;
  siteId: string | null;
  siteName: string | null;
  area: string | null;
  direction: string | null;
  lastSeenAt: string | null;
  lastHandshakeAt: string | null;
  claimedAt: string | null;
  firmwareInfo: string | null;
  rawPunchCount: number;
}

export interface ClaimDeviceRequest {
  siteId: string;
  area: string;
  direction: string;
  name?: string;
}

// --- roster ----------------------------------------------------------------

export interface IclockPerson {
  id: string;
  siteId: string;
  pin: string;
  name: string | null;
  email: string | null;
  companyId: string | null;
  companyName: string | null;
  companyLabel: string | null;
  team: string | null;
  role: string | null;
  lateExemptMin: number;
  active: boolean;
  /** Reporting exclusion only — the person still resolves, promotes and shows on the board. */
  excludedFromReports: boolean;
  employeeId: string | null;
  employeeName: string | null;
  duplicateEmail: boolean;
  unnamed: boolean;
  punchCount: number;
}

export interface UpsertPersonRequest {
  pin: string;
  name?: string | null;
  email?: string | null;
  companyId?: string | null;
  companyLabel?: string | null;
  team?: string | null;
  role?: string | null;
  lateExemptMin?: number | null;
  active?: boolean | null;
  excludedFromReports?: boolean | null;
}

export interface LinkSuggestion {
  employeeId: string;
  employeeName: string | null;
  employeeEmail: string | null;
  employeeStatus: string;
  /** HIGH (exact email) or MEDIUM (normalised name within the resolved company). */
  confidence: string;
  basis: string;
}

// --- import ----------------------------------------------------------------

export interface RosterImportRow {
  pin: string;
  name: string | null;
  email: string | null;
  companyLabel: string | null;
  outcome: string;
  detail: string | null;
}

export interface CompanyTally {
  companyId: string | null;
  companyName: string | null;
  seedLabel: string | null;
  people: number;
}

export interface RosterImportReport {
  committed: boolean;
  total: number;
  created: number;
  updated: number;
  skipped: number;
  companiesMatched: number;
  companiesUnmatched: number;
  unmatchedCompanyLabels: string[];
  duplicateEmails: string[];
  byCompany: CompanyTally[];
  companyless: RosterImportRow[];
  rows: RosterImportRow[];
}

// --- inbox -----------------------------------------------------------------

export interface UnmappedPin {
  pin: string;
  punchCount: number;
  firstSeen: string | null;
  lastSeen: string | null;
  siteId: string | null;
  siteName: string | null;
  reason: string;
  suggestedName: string | null;
  livePunchCount: number;
  inactivePerson: boolean;
  personId: string | null;
}

export interface UnmappedInbox {
  since: string | null;
  live: UnmappedPin[];
  archiveOnlyPins: number;
  archiveOnlyPunches: number;
}

export interface SweepResult {
  scanned: number;
  promoted: number;
  skipped: number;
  byOutcome: string[];
}

export interface ReresolveReport {
  scanned: number;
  promoted: number;
  alreadyDone: number;
  since: string | null;
}

// --- board -----------------------------------------------------------------

export type Presence = 'IN_OFFICE' | 'IN_CAFETERIA' | 'LEFT' | 'NOT_ARRIVED';

export interface PersonChip {
  personId: string;
  name: string | null;
  pin: string;
  companyName: string | null;
  team: string | null;
  presence: Presence;
  lastAt: string | null;
  lastDirection: string | null;
  lastArea: string | null;
}

export interface DeviceHealth {
  serialNumber: string;
  name: string | null;
  direction: string | null;
  status: string;
  lastSeenAt: string | null;
  minutesSinceSeen: number;
  healthy: boolean;
  punchesToday: number;
}

export interface Overview {
  siteId: string;
  siteName: string;
  shiftDate: string;
  rosterSize: number;
  presentNow: number;
  arrived: number;
  notArrived: number;
  lateSoFar: number;
  punchesToday: number;
  devices: DeviceHealth[];
}

export interface Board {
  siteId: string;
  shiftDate: string;
  asOf: string;
  inOffice: PersonChip[];
  inCafeteria: PersonChip[];
  left: PersonChip[];
  notArrived: PersonChip[];
}

export interface DayPunch {
  id: string;
  effectiveAt: string;
  direction: string;
  area: string | null;
  burstCount: number;
  burstFirstAt: string | null;
  burstLastAt: string | null;
  anomaly: string | null;
}

export interface DaySession {
  /**
   * NULLABLE. The board pairs punches by inference, and an OUT with no preceding IN yields a session
   * with no start — `new DaySession(null, effectiveAt, true, cafe)`. Typing this non-nullable let
   * `new Date(null)` fall through to the 1970 epoch and render a half-million-hour session.
   */
  from: string | null;
  to: string | null;
  /** The pairing was inferred, not observed — the console says so rather than imply a clean pair. */
  estimated: boolean;
  cafeteria: boolean;
}

export interface PersonDay {
  personId: string;
  name: string | null;
  pin: string;
  shiftDate: string;
  firstIn: string | null;
  lastOut: string | null;
  punches: DayPunch[];
  sessions: DaySession[];
}

// --- calls -----------------------------------------------------------------

const BASE = '/provisioning/iclock';

export function listSites(signal?: AbortSignal): Promise<IclockSite[]> {
  return apiFetch<IclockSite[]>(`${BASE}/sites`, { signal });
}

export function getSiteDetail(siteId: string, signal?: AbortSignal): Promise<IclockSiteDetail> {
  return apiFetch<IclockSiteDetail>(`${BASE}/sites/${siteId}`, { signal });
}

export function listDevices(status?: string, signal?: AbortSignal): Promise<IclockDevice[]> {
  const qs = status ? `?status=${encodeURIComponent(status)}` : '';
  return apiFetch<IclockDevice[]>(`${BASE}/devices${qs}`, { signal });
}

export function claimDevice(deviceId: string, body: ClaimDeviceRequest): Promise<IclockDevice> {
  return apiFetch<IclockDevice>(`${BASE}/devices/${deviceId}/claim`, { method: 'POST', body });
}

export function unclaimDevice(deviceId: string): Promise<IclockDevice> {
  return apiFetch<IclockDevice>(`${BASE}/devices/${deviceId}/unclaim`, { method: 'POST' });
}

export function listPeople(siteId: string, signal?: AbortSignal): Promise<IclockPerson[]> {
  return apiFetch<IclockPerson[]>(`${BASE}/sites/${siteId}/people`, { signal });
}

export function upsertPerson(siteId: string, body: UpsertPersonRequest): Promise<IclockPerson> {
  return apiFetch<IclockPerson>(`${BASE}/sites/${siteId}/people`, { method: 'POST', body });
}

export function editPerson(personId: string, body: UpsertPersonRequest): Promise<IclockPerson> {
  return apiFetch<IclockPerson>(`${BASE}/people/${personId}`, { method: 'PATCH', body });
}

/** Dry run by default — nothing is written unless `commit` is true. */
export function importRoster(
  siteId: string,
  csv: string,
  commit: boolean,
): Promise<RosterImportReport> {
  return apiFetch<RosterImportReport>(`${BASE}/sites/${siteId}/people/import?commit=${commit}`, {
    method: 'POST',
    body: { csv },
  });
}

export function getSuggestions(personId: string, signal?: AbortSignal): Promise<LinkSuggestion[]> {
  return apiFetch<LinkSuggestion[]>(`${BASE}/people/${personId}/suggestions`, { signal });
}

export function confirmLink(personId: string, employeeId: string): Promise<IclockPerson> {
  return apiFetch<IclockPerson>(`${BASE}/people/${personId}/link`, {
    method: 'POST',
    body: { employeeId },
  });
}

export function unlinkPerson(personId: string): Promise<IclockPerson> {
  return apiFetch<IclockPerson>(`${BASE}/people/${personId}/link`, { method: 'DELETE' });
}

export function getUnmappedInbox(siteId: string, signal?: AbortSignal): Promise<UnmappedInbox> {
  return apiFetch<UnmappedInbox>(`${BASE}/sites/${siteId}/inbox/unmapped`, { signal });
}

export function runSweep(): Promise<SweepResult> {
  return apiFetch<SweepResult>(`${BASE}/promote/sweep`, { method: 'POST' });
}

export function reresolve(siteId: string): Promise<ReresolveReport> {
  return apiFetch<ReresolveReport>(`${BASE}/sites/${siteId}/reresolve`, { method: 'POST' });
}

export function getOverview(siteId: string, signal?: AbortSignal): Promise<Overview> {
  return apiFetch<Overview>(`${BASE}/sites/${siteId}/overview`, { signal });
}

export function getBoard(siteId: string, signal?: AbortSignal): Promise<Board> {
  return apiFetch<Board>(`${BASE}/sites/${siteId}/board`, { signal });
}

export function getPersonDay(
  personId: string,
  shiftDate?: string,
  signal?: AbortSignal,
): Promise<PersonDay> {
  const qs = shiftDate ? `?shiftDate=${encodeURIComponent(shiftDate)}` : '';
  return apiFetch<PersonDay>(`${BASE}/people/${personId}/day${qs}`, { signal });
}

/**
 * Query keys. Grouped under one root so a mutation can invalidate an entire site's console with
 * `queryClient.invalidateQueries({ queryKey: iclockKeys.site(siteId) })` without listing every screen
 * that reads from it.
 */
export const iclockKeys = {
  root: ['iclock'] as const,
  sites: () => ['iclock', 'sites'] as const,
  devices: (status?: string) => ['iclock', 'devices', status ?? 'all'] as const,
  site: (siteId: string) => ['iclock', 'site', siteId] as const,
  people: (siteId: string) => ['iclock', 'site', siteId, 'people'] as const,
  inbox: (siteId: string) => ['iclock', 'site', siteId, 'inbox'] as const,
  overview: (siteId: string) => ['iclock', 'site', siteId, 'overview'] as const,
  board: (siteId: string) => ['iclock', 'site', siteId, 'board'] as const,
  suggestions: (personId: string) => ['iclock', 'person', personId, 'suggestions'] as const,
  personDay: (personId: string, shiftDate?: string) =>
    ['iclock', 'person', personId, 'day', shiftDate ?? 'today'] as const,
};
